### PR TITLE
fixing some issues example script

### PR DESCRIPTION
**Pull request by dieloz**
Dear Ryan,
First of all, thank you very much for sharing your code. I just run your example script and I found few minor issues I'm trying to solve in this pull request. 
You'll see some time variables were missing and I added some support functions that were missing that I found here:
https://github.com/srsummerson/analysis/blob/master/spectrogram/make_center_frequencies.m
https://github.com/saraszcz/ECoG_analysis_functions/blob/master/support_functions/get_signal_parameters.m
I attach you the two figures I got and the workspace output. 
Soon I'll MAGE my EEG data so I can provide you some feedback in case you're interested. 
Please don't hesitate to ask you any question
Diego

[out.mat.tar.gz](https://github.com/rcanolty/MAGE/files/2900246/out.mat.tar.gz)
fig2
fig1

### CODE REVIEW

**Comment by rcanolty** [comment]
Many thanks for the heads-up! I have added my versions of those functions
now. For EEG/ECoG I like a log spacing with a minimum step size, were I to
re-write it now I think I would do constant inner product magnitude between
adjacent filter atoms.

If you have not already investigated it, I would check out the Matching
Pursuit Toolkit (MPTK), which is much faster than my example MP code.

Please let me know if you run into any additional issues, I plan to keep
updating codebase as I clean up my own "personal" code and scripts.

Best,
Ryan

**Comment by dieloz** [comment]
Hi Ryan,
Thank you for your prompt reply! I'll keep you posted but may be I'll wait a bit more since you're still updating the repository.
Best,
Diego

**Comment by rcanolty** [comment]
Hi Diego --

I am about to do some revision to the MAGE code, and I am planning to move
it over to the language Julia (which I do not know very well, but everyone
keeps saying it is MATLAB-like syntax and fast). I wanted to check in with
you to see if you might have applied it to some of your EEG data, and if so
whether you have any feedback I should consider for the code migration.

Also, if you have not tried it, I recommend the matching pursuit package
MPTK. It doesn't look like it is still being maintained, but they knew what
they were doing and coded a fast package with a nice API.

Thanks again for trying out the code originally! Take care.

Best,
Ryan

**Comment by dieloz** [comment]
Thanks for letting me know. I'll take a look early next month
Best

**Pull request closed without merging**
